baseURL = 'https://fik.my.id'
languageCode = 'id'
title = 'Faizal Kusmawan'
theme = 'congo'

[params]
Description = "The personal website and blog about Excel and Google Sheets"

[assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
appleTouchIcon = "/apple-touch-icon.png"