baseURL = 'https://faizalindrak.github.io/'
languageCode = 'id_ID'
title = 'Faizal Kusmawan'
theme = 'papermodified'
defaultTheme = 'light'

[params]
Description = "The personal website and blog about Excel and Google Sheets"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'Arvives'
  name = 'Archives'
  url = '/archives/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'

[params.homeInfoParams]
Title = "Hi there"
Content = "I’m Faizal, a data enthusiast who loves to share my knowledge and experience with you. In this blog, you’ll find useful tips and tricks on how to use Excel, Google Sheets and other tools for data analysis"

[[params.socialIcons]]
name = "github"
url = "https://github.com/faizalindrak/"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/faizalindrak"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/faizalindrak/"

[[params.socialIcons]]
name = "medium"
url = "https://medium.com/@faizalindrak"

    
